webtalk_init -webtalk_dir /user/0/.base/lecampt/home/Desktop/aslounes_lecampt/.CEPcache/sim/xsim.dir/work.tb_PROC/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 12 11:43:57 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4e48ebb4-ad7e-44b6-ac43-8e28b6f3043d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f0b15e82-ab58-4635-85db-cb953b62ed78" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.8.2003 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3666.455 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "12" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.68_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "134116_KB" -context "xsim\\usage"
webtalk_transmit -clientid 125671758 -regid "" -xml /user/0/.base/lecampt/home/Desktop/aslounes_lecampt/.CEPcache/sim/xsim.dir/work.tb_PROC/webtalk/usage_statistics_ext_xsim.xml -html /user/0/.base/lecampt/home/Desktop/aslounes_lecampt/.CEPcache/sim/xsim.dir/work.tb_PROC/webtalk/usage_statistics_ext_xsim.html -wdm /user/0/.base/lecampt/home/Desktop/aslounes_lecampt/.CEPcache/sim/xsim.dir/work.tb_PROC/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
